#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
!pip install pandas

Requirement already satisfied: pandas in d:\cuda projects\practice\data analysis\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in d:\cuda projects\practice\data analysis\venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\cuda projects\practice\data analysis\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\cuda projects\practice\data analysis\venv\lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in d:\cuda projects\practice\data analysis\venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in d:\cuda projects\practice\data analysis\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
## Series
# A Pandas Series is a one-dimensional array-like object that can hold any data type. 
# It is similar to a column in a table.

# regular way of creating series 
data = [1,2,3,4,5]
series = pd.Series(data)
print(type(series))
print()
print(series)

<class 'pandas.core.series.Series'>

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
# Creating Series from dictionary
# key becomes index
# value becomes series elements
data = {'a':1,'b':2,'c':3}
pd.Series(data)

a    1
b    2
c    3
dtype: int64

In [6]:
data=[10,20,30]
index_for_data=['apple','banana','cherry']
pd.Series(data,index = index_for_data)

apple     10
banana    20
cherry    30
dtype: int64

In [7]:
# Dataframe
# DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure 
# with labeled axes (rows and columns).

In [8]:
# Using "dictionary of lists" to create dataframe
data = {
    'name':['Mayank','Saloni','Tushar'],
    'age': [22,24,99],
    'city':['Delhi','Banglore','Florida']
}
df = pd.DataFrame(data)
df

     name  age      city
0  Mayank   22     Delhi
1  Saloni   24  Banglore
2  Tushar   99   Florida

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
## Create a Data frame From a "List of Dictionaries"

data=[
    {'Name':'Mayank','Age':22,'City':'Bangalore'},
    {'Name':'Saloni','Age':24,'City':'Bangalore'},
    {'Name':'Bappy','Age':22,'City':'Bangalore'},
    {'Name':'Jack','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0  Mayank   22  Bangalore
1  Saloni   24  Bangalore
2   Bappy   22  Bangalore
3    Jack   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

Reading the csv and storing into dataframe

In [15]:
df=pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [12]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [18]:
# Accessing Data From Dataframe
df['Sales'].head()

0    754.0
1    110.0
2    398.0
3    522.0
4    869.0
Name: Sales, dtype: float64

In [26]:
# picking up row index
df.loc[0]

Date        2023-01-01
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [29]:
# picking up col index
df.iloc[0]

Date        2023-01-01
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [30]:
df.iloc[0][0]

C:\Users\Mayank\AppData\Local\Temp\ipykernel_10672\2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'2023-01-01'

In [27]:
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [37]:
## Accessing a specified element
# df.at[index,'Col_name']
df.at[2,'Product']

'Product2'

In [36]:
df.at[1,'Sales']

np.float64(110.0)

In [ ]:
## Accessing a specified element using iat
# df.iat[row,col] -> access that element
print(df.iat[2,4])

398.0

In [44]:
### Data MAnipulation with Dataframe
df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [49]:
## Adding a column
try:
    df['Salary']=[50000,60000,70000]
    df
except Exception as ex:
    print(ex)

Length of values (3) does not match length of index (50)

In [56]:
df['Salary'] = 0
df.loc[::,'Salary'] = 50000

In [57]:
df.head(10)

         Date Category  Value   Product  Sales Region  Salary
0  2023-01-01        A   28.0  Product1  754.0   East   50000
1  2023-01-02        B   39.0  Product3  110.0  North   50000
2  2023-01-03        C   32.0  Product2  398.0   East   50000
3  2023-01-04        B    8.0  Product1  522.0   East   50000
4  2023-01-05        B   26.0  Product3  869.0  North   50000
5  2023-01-06        B   54.0  Product3  192.0   West   50000
6  2023-01-07        A   16.0  Product1  936.0   East   50000
7  2023-01-08        C   89.0  Product1  488.0   West   50000
8  2023-01-09        C   37.0  Product3  772.0   West   50000
9  2023-01-10        A   22.0  Product2  834.0   West   50000

In [58]:
## Remove a column
# axis = 0 for row
# axis = 1 for cols
# salary is a column
df.drop('Salary',axis=1,inplace=True)

In [59]:
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [60]:
## Add age to the column
df['Value']=df['Value']+1
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   29.0  Product1  754.0   East
1   2023-01-02        B   40.0  Product3  110.0  North
2   2023-01-03        C   33.0  Product2  398.0   East
3   2023-01-04        B    9.0  Product1  522.0   East
4   2023-01-05        B   27.0  Product3  869.0  North
5   2023-01-06        B   55.0  Product3  192.0   West
6   2023-01-07        A   17.0  Product1  936.0   East
7   2023-01-08        C   90.0  Product1  488.0   West
8   2023-01-09        C   38.0  Product3  772.0   West
9   2023-01-10        A   23.0  Product2  834.0   West
10  2023-01-11        B    8.0  Product1  842.0  North
11  2023-01-12        B   61.0  Product2    NaN   West
12  2023-01-13        A   71.0  Product3  628.0  South
13  2023-01-14        A   70.0  Product1  423.0   East
14  2023-01-15        A   48.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   94.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   32.0  Product2  578.0   West
19  2023-01-20        A   60.0  Product1  736.0   East
20  2023-01-21        C   83.0  Product3  606.0  South
21  2023-01-22        C   38.0  Product2  992.0  South
22  2023-01-23        B   63.0  Product3  942.0  North
23  2023-01-24        C   93.0  Product2  342.0   West
24  2023-01-25        A   25.0  Product2  458.0   East
25  2023-01-26        C   96.0  Product1  584.0   West
26  2023-01-27        C   72.0  Product2  619.0  North
27  2023-01-28        C   57.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   52.0  Product2  737.0  South
30  2023-01-31        B   51.0  Product3  735.0   West
31  2023-02-01        A   18.0  Product2  189.0   West
32  2023-02-02        B   64.0  Product3  338.0  South
33  2023-02-03        C   28.0  Product3    NaN   East
34  2023-02-04        C   71.0  Product3  669.0   West
35  2023-02-05        B   61.0  Product2    NaN   West
36  2023-02-06        C   37.0  Product3  177.0   East
37  2023-02-07        C    3.0  Product1    NaN  North
38  2023-02-08        C   95.0  Product1  408.0  South
39  2023-02-09        A   63.0  Product1  155.0   West
40  2023-02-10        B   16.0  Product1  578.0   East
41  2023-02-11        C   98.0  Product1  256.0   East
42  2023-02-12        A   94.0  Product3  164.0   West
43  2023-02-13        A   44.0  Product3  949.0   East
44  2023-02-14        A   97.0  Product3  830.0   East
45  2023-02-15        B  100.0  Product2  599.0   West
46  2023-02-16        B    7.0  Product1  938.0  South
47  2023-02-17        B   70.0  Product3  143.0   West
48  2023-02-18        C   66.0  Product3  182.0  North
49  2023-02-19        C   12.0  Product3  708.0  North

In [ ]:
# dropping a row 
df.drop(0,inplace=True)
df.head()

         Date Category  Value   Product  Sales Region
1  2023-01-02        B   40.0  Product3  110.0  North
2  2023-01-03        C   33.0  Product2  398.0   East
3  2023-01-04        B    9.0  Product1  522.0   East
4  2023-01-05        B   27.0  Product3  869.0  North
5  2023-01-06        B   55.0  Product3  192.0   West

In [62]:
df=pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [63]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [64]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [65]:
df.info

<bound method DataFrame.info of           Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North>

In [66]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object
Statistical summary:
            Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [ ]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000